<?php
/**
 * ACF Field Group for About Page
 *
 * @package ForestPlanet
 */

if (!function_exists('acf_add_local_field_group')) {
    return;
}

acf_add_local_field_group(array(
    'key' => 'group_about_page',
    'title' => 'About Page Content',
    'fields' => array(
        // Hero Section
        array(
            'key' => 'field_about_hero_section',
            'label' => 'Hero Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_subtitle',
            'label' => 'Subtitle',
            'name' => 'about_subtitle',
            'type' => 'text',
            'instructions' => 'The subtitle text (e.g., "WHAT WE DO")',
            'required' => 0,
            'default_value' => 'WHAT WE DO',
        ),
        array(
            'key' => 'field_about_title',
            'label' => 'Hero Title',
            'name' => 'about_title',
            'type' => 'text',
            'instructions' => 'The main title for the hero section (e.g., "Plant Trees Plant Hope")',
            'required' => 0,
            'default_value' => 'Plant Trees Plant Hope',
        ),
        array(
            'key' => 'field_about_hero_image',
            'label' => 'Hero Image',
            'name' => 'about_hero_image',
            'type' => 'image',
            'instructions' => 'The hero background image',
            'required' => 0,
            'return_format' => 'url',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_about_plant_hope_image',
            'label' => 'Plant Hope Image',
            'name' => 'about_plant_hope_image',
            'type' => 'image',
            'instructions' => 'The Plant Hope image',
            'required' => 0,
            'return_format' => 'url',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_about_main_content',
            'label' => 'Main Content',
            'name' => 'about_main_content',
            'type' => 'textarea',
            'instructions' => 'The main content text below the title',
            'required' => 0,
            'rows' => 8,
            'default_value' => 'We channel support from businesses, individuals, and foundations to cost-effective tree-planting projects. These efforts restore habitats, improve soil, capture carbon, and uplift communities.

Through reforestation, we help secure income, food, and hope for many. Trees enrich soil, preserve water, and foster biodiversity.

We proudly partner with visionary organizations to create lasting impact. Join us in transforming lives and ecosystems through trees.',
        ),
        
        // UN SDG Section
        array(
            'key' => 'field_about_unsdg_section',
            'label' => 'UN SDG Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_unsdg_subtitle',
            'label' => 'UNSDG Subtitle',
            'name' => 'about_unsdg_subtitle',
            'type' => 'text',
            'instructions' => 'The UNSDG section subtitle',
            'required' => 0,
            'default_value' => 'GOALS WE STAND BEHIND',
        ),
        array(
            'key' => 'field_about_unsdg_title',
            'label' => 'UNSDG Title',
            'name' => 'about_unsdg_title',
            'type' => 'text',
            'instructions' => 'The UNSDG section title',
            'required' => 0,
            'default_value' => 'United Nations Sustainable Development Goals',
        ),
        array(
            'key' => 'field_about_unsdg_iframe',
            'label' => 'UNSDG iFrame URL',
            'name' => 'about_unsdg_iframe',
            'type' => 'text',
            'instructions' => 'The UNSDG iframe URL',
            'required' => 0,
            'default_value' => '/interactive-unsdg.html',
        ),
        
        // Timeline Section
        array(
            'key' => 'field_about_timeline_section',
            'label' => 'Timeline Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_timeline_title',
            'label' => 'Timeline Title',
            'name' => 'about_timeline_title',
            'type' => 'text',
            'instructions' => 'The timeline section title',
            'required' => 0,
            'default_value' => 'Our Timeline',
        ),
        array(
            'key' => 'field_about_timeline_default_content',
            'label' => 'Timeline Default Content',
            'name' => 'about_timeline_default_content',
            'type' => 'textarea',
            'instructions' => 'The default content for each timeline entry (if specific year content is empty)',
            'required' => 0,
            'rows' => 5,
            'default_value' => 'Everywhere we travel we see underlying economic forces driving unsustainable behavior. Alternatively, when unsustainable behavior begins to deliver diminishing returns it\'s an opportunity to offer economically viable alternatives that also provide ecological benefits. Decision windows open and close quickly, so the right team with the right ideas and tools needs to be ready.',
        ),
        
        // Timeline Entries (Individual Years)
        array(
            'key' => 'field_about_timeline_2017',
            'label' => '2017 Timeline Content',
            'name' => 'about_timeline_2017',
            'type' => 'group',
            'instructions' => 'Content for 2017 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2017_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2017',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2017_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2017_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2017_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'default_value' => 'Planting fig trees in Morocco',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2018',
            'label' => '2018 Timeline Content',
            'name' => 'about_timeline_2018',
            'type' => 'group',
            'instructions' => 'Content for 2018 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2018_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2018',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2018_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2018_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2018_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2019',
            'label' => '2019 Timeline Content',
            'name' => 'about_timeline_2019',
            'type' => 'group',
            'instructions' => 'Content for 2019 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2019_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2019',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2019_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2019_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2019_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2020',
            'label' => '2020 Timeline Content',
            'name' => 'about_timeline_2020',
            'type' => 'group',
            'instructions' => 'Content for 2020 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2020_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2020',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2020_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2020_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2020_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2021',
            'label' => '2021 Timeline Content',
            'name' => 'about_timeline_2021',
            'type' => 'group',
            'instructions' => 'Content for 2021 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2021_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2021',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2021_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2021_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2021_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2022',
            'label' => '2022 Timeline Content',
            'name' => 'about_timeline_2022',
            'type' => 'group',
            'instructions' => 'Content for 2022 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2022_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2022',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2022_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2022_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2022_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2023',
            'label' => '2023 Timeline Content',
            'name' => 'about_timeline_2023',
            'type' => 'group',
            'instructions' => 'Content for 2023 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2023_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2023_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2023_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2023_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2024',
            'label' => '2024 Timeline Content',
            'name' => 'about_timeline_2024',
            'type' => 'group',
            'instructions' => 'Content for 2024 timeline entry',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2024_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2024',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2024_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2024_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2024_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2025',
            'label' => '2025 Timeline Content',
            'name' => 'about_timeline_2025',
            'type' => 'group',
            'instructions' => 'Content for 2025 timeline entry (optional)',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2025_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2025',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2025_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2025_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2025_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_timeline_2026',
            'label' => '2026 Timeline Content',
            'name' => 'about_timeline_2026',
            'type' => 'group',
            'instructions' => 'Content for 2026 timeline entry (optional)',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_timeline_2026_year',
                    'label' => 'Year',
                    'name' => 'year',
                    'type' => 'text',
                    'default_value' => '2026',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2026_content',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'textarea',
                    'rows' => 4,
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2026_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_timeline_2026_caption',
                    'label' => 'Image Caption',
                    'name' => 'caption',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        
        // Invite Us Section
        array(
            'key' => 'field_about_invite_section',
            'label' => 'Invite Us Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_invite_title',
            'label' => 'Invite Us Title',
            'name' => 'about_invite_title',
            'type' => 'text',
            'instructions' => 'The "Invite Us" section title',
            'required' => 0,
            'default_value' => 'Invite Us',
        ),
        array(
            'key' => 'field_about_invite_content',
            'label' => 'Invite Us Content',
            'name' => 'about_invite_content',
            'type' => 'textarea',
            'instructions' => 'The "Invite Us" section content',
            'required' => 0,
            'rows' => 6,
            'default_value' => 'Invite us to your podcast or event to explore how reforestation combats climate change, revitalizes ecosystems, and empowers communities. Podcasts offer a unique platform for us to share in-depth insights, actionable strategies, and inspiring stories about the transformative power of trees. Whether you\'re hosting in the DMV area or virtually, our team is ready to engage and inspire your audience.',
        ),
        array(
            'key' => 'field_about_spoken_title',
            'label' => 'Where We\'ve Spoken Title',
            'name' => 'about_spoken_title',
            'type' => 'text',
            'instructions' => 'The "Where We\'ve Spoken" section title',
            'required' => 0,
            'default_value' => 'Where We\'ve Spoken',
        ),
        array(
            'key' => 'field_about_podcasts_title',
            'label' => 'Podcasts Title',
            'name' => 'about_podcasts_title',
            'type' => 'text',
            'instructions' => 'The "Podcasts" section title',
            'required' => 0,
            'default_value' => 'Podcasts',
        ),
        
        // Story Cards Section
        array(
            'key' => 'field_about_story_cards_section',
            'label' => 'Story Cards',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        // Story Card 1
        array(
            'key' => 'field_about_story_card_1',
            'label' => 'Story Card 1',
            'name' => 'about_story_card_1',
            'type' => 'group',
            'instructions' => 'Content for story card 1',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_1_image',
                    'label' => 'Image',
                    'name' => 'story_card_1_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_1_date',
                    'label' => 'Date',
                    'name' => 'story_card_1_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_1_title',
                    'label' => 'Title',
                    'name' => 'story_card_1_title',
                    'type' => 'text',
                    'default_value' => 'Title For Story Card Template',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_1_content',
                    'label' => 'Content',
                    'name' => 'story_card_1_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Here would contain a brief introduction to the article like the first',
                    'required' => 0,
                ),
            ),
        ),
        // Story Card 2
        array(
            'key' => 'field_about_story_card_2',
            'label' => 'Story Card 2',
            'name' => 'about_story_card_2',
            'type' => 'group',
            'instructions' => 'Content for story card 2',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_2_image',
                    'label' => 'Image',
                    'name' => 'story_card_2_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_2_date',
                    'label' => 'Date',
                    'name' => 'story_card_2_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_2_title',
                    'label' => 'Title',
                    'name' => 'story_card_2_title',
                    'type' => 'text',
                    'default_value' => 'Additional Story Card 1',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_2_content',
                    'label' => 'Content',
                    'name' => 'story_card_2_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Additional content for story card 1.',
                    'required' => 0,
                ),
            ),
        ),
        // Story Card 3
        array(
            'key' => 'field_about_story_card_3',
            'label' => 'Story Card 3',
            'name' => 'about_story_card_3',
            'type' => 'group',
            'instructions' => 'Content for story card 3',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_3_image',
                    'label' => 'Image',
                    'name' => 'story_card_3_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_3_date',
                    'label' => 'Date',
                    'name' => 'story_card_3_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_3_title',
                    'label' => 'Title',
                    'name' => 'story_card_3_title',
                    'type' => 'text',
                    'default_value' => 'Additional Story Card 2',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_3_content',
                    'label' => 'Content',
                    'name' => 'story_card_3_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Additional content for story card 2.',
                    'required' => 0,
                ),
            ),
        ),
        // Story Card 4
        array(
            'key' => 'field_about_story_card_4',
            'label' => 'Story Card 4',
            'name' => 'about_story_card_4',
            'type' => 'group',
            'instructions' => 'Content for story card 4',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_4_image',
                    'label' => 'Image',
                    'name' => 'story_card_4_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_4_date',
                    'label' => 'Date',
                    'name' => 'story_card_4_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_4_title',
                    'label' => 'Title',
                    'name' => 'story_card_4_title',
                    'type' => 'text',
                    'default_value' => 'Additional Story Card 3',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_4_content',
                    'label' => 'Content',
                    'name' => 'story_card_4_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Additional content for story card 3.',
                    'required' => 0,
                ),
            ),
        ),
        // Story Card 5
        array(
            'key' => 'field_about_story_card_5',
            'label' => 'Story Card 5',
            'name' => 'about_story_card_5',
            'type' => 'group',
            'instructions' => 'Content for story card 5',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_5_image',
                    'label' => 'Image',
                    'name' => 'story_card_5_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_5_date',
                    'label' => 'Date',
                    'name' => 'story_card_5_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_5_title',
                    'label' => 'Title',
                    'name' => 'story_card_5_title',
                    'type' => 'text',
                    'default_value' => 'Additional Story Card 4',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_5_content',
                    'label' => 'Content',
                    'name' => 'story_card_5_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Additional content for story card 4.',
                    'required' => 0,
                ),
            ),
        ),
        // Story Card 6
        array(
            'key' => 'field_about_story_card_6',
            'label' => 'Story Card 6',
            'name' => 'about_story_card_6',
            'type' => 'group',
            'instructions' => 'Content for story card 6',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_story_card_6_image',
                    'label' => 'Image',
                    'name' => 'story_card_6_image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_6_date',
                    'label' => 'Date',
                    'name' => 'story_card_6_date',
                    'type' => 'text',
                    'default_value' => 'FEB 16 2023',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_6_title',
                    'label' => 'Title',
                    'name' => 'story_card_6_title',
                    'type' => 'text',
                    'default_value' => 'Additional Story Card 5',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_story_card_6_content',
                    'label' => 'Content',
                    'name' => 'story_card_6_content',
                    'type' => 'textarea',
                    'rows' => 3,
                    'default_value' => 'Additional content for story card 5.',
                    'required' => 0,
                ),
            ),
        ),
        
        // Team Section
        array(
            'key' => 'field_about_team_section',
            'label' => 'Team Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_team_title',
            'label' => 'Team Title',
            'name' => 'about_team_title',
            'type' => 'text',
            'instructions' => 'The "Our Team" section title',
            'required' => 0,
            'default_value' => 'Our Team',
        ),
        array(
            'key' => 'field_about_team_content',
            'label' => 'Team Content',
            'name' => 'about_team_content',
            'type' => 'textarea',
            'instructions' => 'The "Our Team" section content',
            'required' => 0,
            'rows' => 6,
            'default_value' => 'Our dedicated Board of Directors brings together a wealth of experience, vision, and passion for sustainability and global impact. With backgrounds spanning environmental science, business leadership, and community development, they guide our mission to restore ecosystems, empower communities, and drive meaningful change. Their commitment ensures transparency, innovation, and long-term success in all we do.',
        ),
        array(
            'key' => 'field_about_team_member_1',
            'label' => 'Team Member 1',
            'name' => 'about_team_member_1',
            'type' => 'group',
            'instructions' => 'First team member details',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_team_member_1_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_1_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'default_value' => 'EXECUTIVE DIRECTOR',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_1_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'default_value' => 'Hank Dearden',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_team_member_2',
            'label' => 'Team Member 2',
            'name' => 'about_team_member_2',
            'type' => 'group',
            'instructions' => 'Second team member details',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_team_member_2_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_2_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'default_value' => 'COMMUNICATIONS MANAGER',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_2_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'default_value' => 'Annie Acosta',
                    'required' => 0,
                ),
            ),
        ),
        array(
            'key' => 'field_about_team_member_3',
            'label' => 'Team Member 3',
            'name' => 'about_team_member_3',
            'type' => 'group',
            'instructions' => 'Third team member details (optional)',
            'required' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_about_team_member_3_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_3_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_about_team_member_3_name',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 0,
                ),
            ),
        ),
        
        // Call to Action Section
        array(
            'key' => 'field_about_cta_section',
            'label' => 'Call to Action Section',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'placement' => 'top',
        ),
        array(
            'key' => 'field_about_cta_subtitle',
            'label' => 'CTA Subtitle',
            'name' => 'about_cta_subtitle',
            'type' => 'text',
            'instructions' => 'The CTA section subtitle',
            'required' => 0,
            'default_value' => 'ACT NOW',
        ),
        array(
            'key' => 'field_about_cta_title_first',
            'label' => 'CTA Title First Part',
            'name' => 'about_cta_title_first',
            'type' => 'text',
            'instructions' => 'The first part of the CTA title',
            'required' => 0,
            'default_value' => 'Be The',
        ),
        array(
            'key' => 'field_about_cta_title_second',
            'label' => 'CTA Title Second Part',
            'name' => 'about_cta_title_second',
            'type' => 'text',
            'instructions' => 'The second part of the CTA title',
            'required' => 0,
            'default_value' => 'Change',
        ),
        array(
            'key' => 'field_about_cta_content',
            'label' => 'CTA Content',
            'name' => 'about_cta_content',
            'type' => 'textarea',
            'instructions' => 'The CTA section content',
            'required' => 0,
            'rows' => 6,
            'default_value' => 'Your support is the root of transformation. Every donation, every action, and every partnership helps us plant more trees, restore more ecosystems, and uplift more lives.

Donate today to make an immediate impact, or join us as a volunteer or partner to grow a greener, brighter future. Together, we can heal the planet—one tree at a time.',
        ),
        array(
            'key' => 'field_about_cta_image',
            'label' => 'CTA Image',
            'name' => 'about_cta_image',
            'type' => 'image',
            'instructions' => 'The CTA section image',
            'required' => 0,
            'return_format' => 'url',
            'preview_size' => 'medium',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-about.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => true,
)); 