<?php
/**
 * ACF Fields for Front Page
 *
 * Defines the ACF field groups for the front page
 *
 * @package ForestPlanet
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// This is the most critical check
if (!function_exists('acf_add_local_field_group')) {
    return;
}

/**
 * Register ACF fields for Front Page
 */
acf_add_local_field_group(array(
    'key' => 'group_front_page_hero',
    'title' => 'Front Page - Hero Section',
    'fields' => array(
        array(
            'key' => 'field_hero_title',
            'label' => 'Hero Title',
            'name' => 'hero_title',
            'type' => 'text',
            'instructions' => 'Enter the main hero title',
            'required' => 1,
            'default_value' => 'Plant a Tree For Just 15¢',
        ),
        array(
            'key' => 'field_hero_description',
            'label' => 'Hero Description',
            'name' => 'hero_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description text below the hero title',
            'required' => 1,
            'default_value' => 'Welcome to ForestPlanet, a growing organization making low-cost reforestation accessible and impactful.',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_hero_image',
            'label' => 'Hero Image',
            'name' => 'hero_image',
            'type' => 'image',
            'instructions' => 'Upload the main hero image',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => get_option('page_on_front'),
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_what_we_do',
    'title' => 'Front Page - What We Do Section',
    'fields' => array(
        array(
            'key' => 'field_what_we_do_subtitle',
            'label' => 'What We Do Subtitle',
            'name' => 'what_we_do_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle (e.g., "WHAT WE DO")',
            'required' => 0,
            'default_value' => 'WHAT WE DO',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_what_we_do_title',
            'label' => 'What We Do Title',
            'name' => 'what_we_do_title',
            'type' => 'text',
            'instructions' => 'Enter the title (e.g., "Plant Trees, Plant Hope")',
            'required' => 0,
            'default_value' => 'Plant Trees, Plant Hope',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_what_we_do_description',
            'label' => 'What We Do Description',
            'name' => 'what_we_do_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description text for this section',
            'required' => 0,
            'default_value' => 'We channel support from businesses, individuals, and foundations to cost-effective tree-planting projects. These efforts restore habitats, improve soil, capture carbon, and uplift communities.

Through reforestation, we help secure income, food, and hope for many. Trees enrich soil, preserve water, and foster biodiversity.

We proudly partner with visionary organizations to create lasting impact. Join us in transforming lives and ecosystems through trees.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 8,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_what_we_do_image',
            'label' => 'What We Do Image',
            'name' => 'what_we_do_image',
            'type' => 'image',
            'instructions' => 'Upload the image for this section (e.g., "Tanzania FP Sign")',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_impact_metrics',
    'title' => 'Front Page - Impact Metrics',
    'fields' => array(
        array(
            'key' => 'field_impact_subtitle',
            'label' => 'Impact Section Subtitle',
            'name' => 'impact_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle for the impact section (e.g., "OUR IMPACT")',
            'required' => 0,
            'default_value' => 'OUR IMPACT',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Impact Metric 1
        array(
            'key' => 'field_metric_1_number',
            'label' => 'Metric 1 Number',
            'name' => 'metric_1_number',
            'type' => 'text',
            'instructions' => 'Enter the first metric number (e.g., "1.4m")',
            'required' => 0,
            'default_value' => '1.4m',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_metric_1_label',
            'label' => 'Metric 1 Label',
            'name' => 'metric_1_label',
            'type' => 'text',
            'instructions' => 'Enter the first metric label (e.g., "Trees")',
            'required' => 0,
            'default_value' => 'Trees',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Impact Metric 2
        array(
            'key' => 'field_metric_2_number',
            'label' => 'Metric 2 Number',
            'name' => 'metric_2_number',
            'type' => 'text',
            'instructions' => 'Enter the second metric number (e.g., "3")',
            'required' => 0,
            'default_value' => '3',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_metric_2_label',
            'label' => 'Metric 2 Label',
            'name' => 'metric_2_label',
            'type' => 'text',
            'instructions' => 'Enter the second metric label (e.g., "Countries")',
            'required' => 0,
            'default_value' => 'Countries',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Impact Metric 3
        array(
            'key' => 'field_metric_3_number',
            'label' => 'Metric 3 Number',
            'name' => 'metric_3_number',
            'type' => 'text',
            'instructions' => 'Enter the third metric number (e.g., "10")',
            'required' => 0,
            'default_value' => '10',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_metric_3_label',
            'label' => 'Metric 3 Label',
            'name' => 'metric_3_label',
            'type' => 'text',
            'instructions' => 'Enter the third metric label (e.g., "Partners")',
            'required' => 0,
            'default_value' => 'Partners',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Impact Metric 4
        array(
            'key' => 'field_metric_4_number',
            'label' => 'Metric 4 Number',
            'name' => 'metric_4_number',
            'type' => 'text',
            'instructions' => 'Enter the fourth metric number (e.g., "5")',
            'required' => 0,
            'default_value' => '5',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_metric_4_label',
            'label' => 'Metric 4 Label',
            'name' => 'metric_4_label',
            'type' => 'text',
            'instructions' => 'Enter the fourth metric label (e.g., "Projects")',
            'required' => 0,
            'default_value' => 'Projects',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 20,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_map',
    'title' => 'Front Page - Map Section',
    'fields' => array(
        array(
            'key' => 'field_map_subtitle',
            'label' => 'Map Section Subtitle',
            'name' => 'map_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle for the map section (e.g., "WHERE WE\'VE BEEN")',
            'required' => 0,
            'default_value' => 'WHERE WE\'VE BEEN',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_map_title',
            'label' => 'Map Section Title',
            'name' => 'map_title',
            'type' => 'text',
            'instructions' => 'Enter the title for the map section (e.g., "Where We\'ve Impacted")',
            'required' => 0,
            'default_value' => 'Where We\'ve Impacted',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 30,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_problem_solved',
    'title' => 'Front Page - Problem Solved Section',
    'fields' => array(
        array(
            'key' => 'field_problem_solved_subtitle',
            'label' => 'Problem Solved Subtitle',
            'name' => 'problem_solved_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle for this section (e.g., "SEE THE DIFFERENCE")',
            'required' => 0,
            'default_value' => 'SEE THE DIFFERENCE',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_problem_solved_title',
            'label' => 'Problem Solved Title',
            'name' => 'problem_solved_title',
            'type' => 'text',
            'instructions' => 'Enter the title for this section (e.g., "Problem? Solved.")',
            'required' => 0,
            'default_value' => 'Problem? Solved.',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_problem_description',
            'label' => 'Problem Description',
            'name' => 'problem_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description text for this section',
            'required' => 0,
            'default_value' => 'Before: Degraded landscapes, barren soils, and disappearing wildlife.
After: Flourishing forests, enriched soil, vibrant habitats, and cleaner air.

Every tree planted turns desolation into life, combating climate change and creating a healthier, greener planet for future generations.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_before_image',
            'label' => 'Before Image',
            'name' => 'before_image',
            'type' => 'image',
            'instructions' => 'Upload the "before" image for the comparison slider',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        array(
            'key' => 'field_after_image',
            'label' => 'After Image',
            'name' => 'after_image',
            'type' => 'image',
            'instructions' => 'Upload the "after" image for the comparison slider',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 40,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_partners',
    'title' => 'Front Page - Partners Section',
    'fields' => array(
        array(
            'key' => 'field_partners_title',
            'label' => 'Partners Section Title',
            'name' => 'partners_title',
            'type' => 'text',
            'instructions' => 'Enter the title for the partners section (e.g., "Our Partners")',
            'required' => 0,
            'default_value' => 'Our Partners',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 50,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_impact_steps',
    'title' => 'Front Page - Impact Steps Section',
    'fields' => array(
        array(
            'key' => 'field_impact_steps_title',
            'label' => 'Impact Steps Title',
            'name' => 'impact_steps_title',
            'type' => 'text',
            'instructions' => 'Enter the title for this section (e.g., "How Your Support Drives Impact")',
            'required' => 0,
            'default_value' => 'How Your Support Drives Impact',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Step 1
        array(
            'key' => 'field_step_1_title',
            'label' => 'Step 1 Title',
            'name' => 'step_1_title',
            'type' => 'text',
            'instructions' => 'Enter the title for Step 1',
            'required' => 0,
            'default_value' => 'Funding Tree Planting Projects',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_step_1_description',
            'label' => 'Step 1 Description',
            'name' => 'step_1_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for Step 1',
            'required' => 0,
            'default_value' => 'Your donations directly fund large-scale tree planting initiatives with proven success across the globe.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_step_1_image',
            'label' => 'Step 1 Image',
            'name' => 'step_1_image',
            'type' => 'image',
            'instructions' => 'Upload the image for Step 1',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        // Step 2
        array(
            'key' => 'field_step_2_title',
            'label' => 'Step 2 Title',
            'name' => 'step_2_title',
            'type' => 'text',
            'instructions' => 'Enter the title for Step 2',
            'required' => 0,
            'default_value' => 'Supporting Local Communities',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_step_2_description',
            'label' => 'Step 2 Description',
            'name' => 'step_2_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for Step 2',
            'required' => 0,
            'default_value' => 'Contributions create jobs, improve food security, and generate hope for communities living on the edge of poverty.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_step_2_image',
            'label' => 'Step 2 Image',
            'name' => 'step_2_image',
            'type' => 'image',
            'instructions' => 'Upload the image for Step 2',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        // Step 3
        array(
            'key' => 'field_step_3_title',
            'label' => 'Step 3 Title',
            'name' => 'step_3_title',
            'type' => 'text',
            'instructions' => 'Enter the title for Step 3',
            'required' => 0,
            'default_value' => 'Restoring Ecosystems',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_step_3_description',
            'label' => 'Step 3 Description',
            'name' => 'step_3_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for Step 3',
            'required' => 0,
            'default_value' => 'Each tree planted helps restore wildlife habitats, enrich soils, and combat climate change through carbon sequestration.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_step_3_image',
            'label' => 'Step 3 Image',
            'name' => 'step_3_image',
            'type' => 'image',
            'instructions' => 'Upload the image for Step 3',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        // Step 4
        array(
            'key' => 'field_step_4_title',
            'label' => 'Step 4 Title',
            'name' => 'step_4_title',
            'type' => 'text',
            'instructions' => 'Enter the title for Step 4',
            'required' => 0,
            'default_value' => 'Long-Term Sustainability',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_step_4_description',
            'label' => 'Step 4 Description',
            'name' => 'step_4_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for Step 4',
            'required' => 0,
            'default_value' => 'Your participation fuels ongoing projects that ensure long-lasting environmental and social benefits, making a lasting difference.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_step_4_image',
            'label' => 'Step 4 Image',
            'name' => 'step_4_image',
            'type' => 'image',
            'instructions' => 'Upload the image for Step 4',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 60,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_testimonials',
    'title' => 'Front Page - Testimonials Section',
    'fields' => array(
        array(
            'key' => 'field_testimonials_subtitle',
            'label' => 'Testimonials Subtitle',
            'name' => 'testimonials_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle for the testimonials section (e.g., "WHAT PEOPLE ARE SAYING")',
            'required' => 0,
            'default_value' => 'WHAT PEOPLE ARE SAYING',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_testimonials_title',
            'label' => 'Testimonials Title',
            'name' => 'testimonials_title',
            'type' => 'text',
            'instructions' => 'Enter the title for the testimonials section (e.g., "Testimonials")',
            'required' => 0,
            'default_value' => 'Testimonials',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Testimonial 1
        array(
            'key' => 'field_testimonial_1_name',
            'label' => 'Testimonial 1 Name',
            'name' => 'testimonial_1_name',
            'type' => 'text',
            'instructions' => 'Enter the name for testimonial 1',
            'required' => 0,
            'default_value' => 'Person Name - Partner',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_testimonial_1_quote',
            'label' => 'Testimonial 1 Quote',
            'name' => 'testimonial_1_quote',
            'type' => 'textarea',
            'instructions' => 'Enter the quote for testimonial 1',
            'required' => 0,
            'default_value' => 'Partnering with this initiative has been incredible. Every tree planted is not just a step toward a greener planet, but a step toward hope for countless communities. It\'s rewarding to see tangible change.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'br',
        ),
        // Testimonial 2
        array(
            'key' => 'field_testimonial_2_name',
            'label' => 'Testimonial 2 Name',
            'name' => 'testimonial_2_name',
            'type' => 'text',
            'instructions' => 'Enter the name for testimonial 2',
            'required' => 0,
            'default_value' => 'Person Name - Partner',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_testimonial_2_quote',
            'label' => 'Testimonial 2 Quote',
            'name' => 'testimonial_2_quote',
            'type' => 'textarea',
            'instructions' => 'Enter the quote for testimonial 2',
            'required' => 0,
            'default_value' => 'Partnering with this initiative has been incredible. Every tree planted is not just a step toward a greener planet, but a step toward hope for countless communities. It\'s rewarding to see tangible change.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'br',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 70,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_get_involved',
    'title' => 'Front Page - Get Involved Section',
    'fields' => array(
        array(
            'key' => 'field_get_involved_title',
            'label' => 'Get Involved Title',
            'name' => 'get_involved_title',
            'type' => 'text',
            'instructions' => 'Enter the title for the Get Involved section (e.g., "Get Involved")',
            'required' => 0,
            'default_value' => 'Get Involved',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        // Option 1 - Partner
        array(
            'key' => 'field_option_1_for',
            'label' => 'Option 1 For',
            'name' => 'option_1_for',
            'type' => 'text',
            'instructions' => 'Enter the target audience for option 1 (e.g., "FOR BUSINESSES")',
            'required' => 0,
            'default_value' => 'FOR BUSINESSES',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_1_title',
            'label' => 'Option 1 Title',
            'name' => 'option_1_title',
            'type' => 'text',
            'instructions' => 'Enter the title for option 1 (e.g., "Partner")',
            'required' => 0,
            'default_value' => 'Partner',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_1_description',
            'label' => 'Option 1 Description',
            'name' => 'option_1_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for option 1',
            'required' => 0,
            'default_value' => 'Show your commitment to sustainability by partnering with us. Together, we can drive environmental restoration and social change.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        // Option 2 - Donate
        array(
            'key' => 'field_option_2_for',
            'label' => 'Option 2 For',
            'name' => 'option_2_for',
            'type' => 'text',
            'instructions' => 'Enter the target audience for option 2 (e.g., "FOR INDIVIDUALS")',
            'required' => 0,
            'default_value' => 'FOR INDIVIDUALS',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_2_title',
            'label' => 'Option 2 Title',
            'name' => 'option_2_title',
            'type' => 'text',
            'instructions' => 'Enter the title for option 2 (e.g., "Donate")',
            'required' => 0,
            'default_value' => 'Donate',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_2_description',
            'label' => 'Option 2 Description',
            'name' => 'option_2_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for option 2',
            'required' => 0,
            'default_value' => 'Every dollar plants trees, restores ecosystems, and supports communities in need. Your contribution makes an immediate and lasting impact.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        // Option 3 - Invite Us
        array(
            'key' => 'field_option_3_for',
            'label' => 'Option 3 For',
            'name' => 'option_3_for',
            'type' => 'text',
            'instructions' => 'Enter the target audience for option 3 (e.g., "FOR BUSINESSES")',
            'required' => 0,
            'default_value' => 'FOR BUSINESSES',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_3_title',
            'label' => 'Option 3 Title',
            'name' => 'option_3_title',
            'type' => 'text',
            'instructions' => 'Enter the title for option 3 (e.g., "Invite Us")',
            'required' => 0,
            'default_value' => 'Invite Us',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_option_3_description',
            'label' => 'Option 3 Description',
            'name' => 'option_3_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for option 3',
            'required' => 0,
            'default_value' => 'Invite us to your event to share insights on how reforestation combats climate change and uplifts communities.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 80,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_stories',
    'title' => 'Front Page - Stories Section',
    'fields' => array(
        array(
            'key' => 'field_stories_title',
            'label' => 'Stories Section Title',
            'name' => 'stories_title',
            'type' => 'text',
            'instructions' => 'Enter the title for the stories section (e.g., "Our Stories")',
            'required' => 0,
            'default_value' => 'Our Stories',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 90,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

acf_add_local_field_group(array(
    'key' => 'group_front_page_act_now',
    'title' => 'Front Page - Act Now Section',
    'fields' => array(
        array(
            'key' => 'field_act_now_subtitle',
            'label' => 'Act Now Subtitle',
            'name' => 'act_now_subtitle',
            'type' => 'text',
            'instructions' => 'Enter the subtitle for this section (e.g., "ACT NOW")',
            'required' => 0,
            'default_value' => 'ACT NOW',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_act_now_title',
            'label' => 'Act Now Title',
            'name' => 'act_now_title',
            'type' => 'text',
            'instructions' => 'Enter the title for this section (e.g., "Be The Change")',
            'required' => 0,
            'default_value' => 'Be The Change',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_act_now_description',
            'label' => 'Act Now Description',
            'name' => 'act_now_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description for this section',
            'required' => 0,
            'default_value' => 'Your support is the root of transformation. Every donation, every action, and every partnership helps us plant more trees, restore more ecosystems, and uplift more lives.
Donate today to make an immediate impact, or join us as a volunteer or partner to grow a greener, brighter future. Together, we can heal the planet—one tree at a time.',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_act_now_image',
            'label' => 'Act Now Image',
            'name' => 'act_now_image',
            'type' => 'image',
            'instructions' => 'Upload the image for this section',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 100,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

// Simple test group (for troubleshooting)
acf_add_local_field_group(array(
    'key' => 'group_front_page_test',
    'title' => 'Front Page - Test Field Group',
    'fields' => array(
        array(
            'key' => 'field_test_text',
            'label' => 'Test Text Field',
            'name' => 'test_text',
            'type' => 'text',
            'instructions' => 'This is just a test field',
            'required' => 0,
            'default_value' => 'Test Value',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 999,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'active' => true,
)); 